version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - /etc/letsencrypt/live/example.com/fullchain.pem:/cert.pem:ro
      - /etc/letsencrypt/live/example.com/privkey.pem:/privkey.pem:ro
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.example.com
      - traefik.port=8080

  postgres:
    restart: unless-stopped
    env_file: .env
    image: postgres:9.4
    volumes:
      - /var/data/funkwhale/data/postgres:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    env_file: .env
    image: redis:3
    volumes:
      - /var/data/funkwhale/data/redis:/data

  celeryworker:
    restart: unless-stopped
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION:-latest}
    env_file: .env
    command: celery -A funkwhale_api.taskapp worker -l INFO
    links:
      - postgres
      - redis
    environment:
      - C_FORCE_ROOT=true
    volumes:
      - "${MUSIC_DIRECTORY_SERVE_PATH-/srv/funkwhale/data/music}:${MUSIC_DIRECTORY_PATH-/music}:ro"
      - "${MEDIA_ROOT}:${MEDIA_ROOT}"

  celerybeat:
    restart: unless-stopped
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION:-latest}
    env_file: .env
    command: celery -A funkwhale_api.taskapp beat -l INFO
    links:
      - postgres
      - redis

  api:
    restart: unless-stopped
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION:-latest}
    env_file: .env
    container_name: funkwhale-api
    volumes:
      - "${MUSIC_DIRECTORY_SERVE_PATH-/srv/funkwhale/data/music}:${MUSIC_DIRECTORY_PATH-/music}:ro"
      - "${MEDIA_ROOT}:${MEDIA_ROOT}"
      - "${STATIC_ROOT}:${STATIC_ROOT}"
      - ./front/dist:/frontend
    ports:
      - "${FUNKWHALE_API_IP:-127.0.0.1}:${FUNKWHALE_API_PORT:-5000}:5000"
    links:
      - postgres
      - redis

  funkwhale-frontend:
    image: nginx:1.15.2-alpine
    container_name: funkwhale-frontend
    restart: always
    privileged: true
    volumes:
      - ./html:/var/www/html
      - ./custom:/srv/funkwhale/custom
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./funkwhale_proxy.conf:/etc/nginx/funkwhale_proxy.conf
      - /var/data/funkwhale/data/media:/srv/funkwhale/data/media
      - /var/data/funkwhale/data/static:/srv/funkwhale/data/static
      - /var/data/funkwhale/data/music:/srv/funkwhale/data/music:ro
    labels:
      - traefik.enable=true
      - traefik.backend=music.example.com
      - traefik.frontend.rule=Host:music.example.com
      - traefik.docker.network=proxy
      - traefik.port=80
    ports:
      - 8881:80
    expose: 
      - "8080"
